### ISSUE TITLE
create homebrew formula

### ISSUE THREAD

**Issue by jeantil** [jeantil/autokbisw#13]
it would be nice to have a homebrew formula to install and update autokbisw

however it is unclear to me how to proceed on this topic for now. I will investigate https://github.com/shtirlic/yubikeylockd

Help is welcome :D

**Comment by jeantil** [comment]
This was started by @ratkins in #19

**Comment by ratkins** [comment]
I hadn't even noticed this issue when I started :-)

I submitted the formula to `homebrew-core` but it was [rejected on 'notability' grounds](https://github.com/Homebrew/homebrew-core/pull/33166#issuecomment-431316374). The next option is to maintain a [tap](https://docs.brew.sh/Taps), which is simply a 3rd-party homebrew repository. This requires the creation of a repo called `homebrew-foo` on GitHub, in order to use the short form of `brew install user/foo/autokbisw` to install.

Would you like to create that repository under your GitHub user or shall I? If you want to own it, I'll submit a PR with the formula added.

**Comment by ratkins** [comment]
Installing the bottle from the binary release currently fails, as the actual `autokbisw` binary ends up in `/usr/local/Cellar/autokbisw/1.2.0/` (instead of `.../bin/`.) The real fix for this is generating the bottle "properly" and I'm still working out [how this should be done](https://discourse.brew.sh/t/couldnt-tap-github-repo-without-homebrew-prefix/3178/3?u=ratkins).

**Comment by ratkins** [comment]
That's ok, I get the impression there is a brew command that's meant to generate the bottle for you, but I can't work out how to [spell it right](https://discourse.brew.sh/t/how-do-i-build-a-bottle-for-a-tap/3279).

**Comment by ratkins** [comment]
Ok, I think this is it:
```
brew uninstall autokbisw && brew untap jeantil/autokbisw
brew install --build-from-source --build-bottle jeantil/autokbisw/autokbisw
brew bottle --root-url="https://github.com/jeantil/autokbisw/releases/download/1.2.0/" --no-rebuild autokbisw
```
The above is your release process once you've made a new source release. It'll give you a `bottle do ...` stanza you can update the formula with, and a `...bottle.tar.gz` binary you can upload to the GitHub releases page. At this point you might actually want to omit the `--no-rebuild` option, which I think tells clients there's a binary rebuild of the same nominal version and there is still something to update if they do a `brew update`.

If you're able to do that, merge the resulting bottle stanza into the formula and upload the new binary I think we can call this one done.

**Comment by ratkins** [comment]
*gentle nudge*, @jeantil

**Comment by jeantil** [comment]
I have absolutely NaN time to handle this :(

**Comment by ratkins** [comment]
I just tested locally and can confirm it works—so I think you can now close this one as solved! 👌
