### ISSUE TITLE
Apple M1: can't install via Homebrew

### ISSUE THREAD

**Issue by Airmonkdev** [jeantil/autokbisw#29]
Hello,
first of all many thanks for all you've done!

I've just changed my Intel MacBook for the new M1 MacBook and it seems that autokbisw can't be installed using Homebrew:

I've run "brew install jeantil/autokbisw/autokbisw" and here there is the error

----------------------------------------
....
swift
build
-c
release
-Xswiftc
-static-stdlib
--disable-sandbox

Fetching https://github.com/apple/swift-package-manager
Cloning https://github.com/apple/swift-package-manager
Resolving https://github.com/apple/swift-package-manager at 0.3.0
[1/2] Compiling clibc libc.c
<unknown>:0: error: -static-stdlib is no longer supported on Apple platforms
Do not report this issue to Homebrew/brew or Homebrew/core!
----------------------------------------

**Comment by jeantil** [comment]
hi @Airmonkdev 

I'm sorry but not surprised that it doesn't work. M1 has a significant plaform change.  However, this project is no [longer actively maintained ](https://github.com/jeantil/autokbisw#this-project-is-looking-for-a-maintainer) as I haven't owned a mac for about 2 years now :)
if you want to pick it up you are very much welcome to do so.

**Comment by Airmonkdev** [comment]
Auch! Unfortunately I'm not so expert to fix that issue. 
Coul you please consider to help me get it work!? I'll really appreciate because your app is really great and exactly what I'm looking for

**Comment by tinwhisker** [comment]
@Airmonkdev 

You probably already figured this, but might help someone else too. Pretty much verbatim the readme, but small tweaks that you may otherwise trip on:

From terminal:

Move to a directory you want to use (i.e. Desktop): cd `~/Desktop`

`
git clone https://github.com/jeantil/autokbisw.git
cd autokbisw
swift build --configuration release
cp ${PWD}/.build/release/autokbisw /usr/local/bin/
cp eu.byjean.autokbisw.plist ~/Library/LaunchAgents/
launchctl load ~/Library/LaunchAgents/eu.byjean.autokbisw.plist
`
Then reboot.

I don't know if you need to 'train' the service, but I selected the keymap and typed something on the Mac keyboard, then
switched keymap and typed on the other.
Afterward, it'll pick the keymap after the first key (so just tap an inert key like 'shift' or 'control').

Worse case, you can tap the Mac 'fn' key if it has a world symbol, to cycle the keymaps.

**Comment by jeantil** [comment]
hello, you may want to have a look @ohueter's fork https://github.com/ohueter/autokbisw he has fixed the build for newer versions of OSX not sure if he hase gone as far as homebrew though.
